In [1]:
import tensorflow as tf

In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


### initilize constant

In [3]:
a=tf.constant('tensor')
b=tf.constant('flow')
#for run first create a sesion then run
#first method create a session
with tf.Session() as ses:
    print(ses.run(a+b))

b'tensorflow'


In [4]:
#second method
ses=tf.Session()
print(ses.run(a+b))

b'tensorflow'


In [5]:
#
sess = tf.InteractiveSession()
print(sess.run(a+b))

b'tensorflow'


### INITILIZE VARIABLE

In [6]:
#INITILIZE VARIABLE
sess=tf.InteractiveSession()
a=tf.Variable(2)
b=tf.Variable(3)

c=a+b
print(a)
print(sess.run(a))

C:\Users\ujjal\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\client\session.py:1752: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


<tf.Variable 'Variable:0' shape=() dtype=int32_ref>


FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[{{node _retval_Variable_0_0}}]]

In [7]:
## for print variable first initlize 
intilizer=tf.global_variables_initializer()
sess.run(intilizer)
print(sess.run(a))
print(sess.run(a+b))
print(sess.run(c))

2
5
5


### Placeholders 
 A placeholder is simply a variable that we will assign data to at a later date

In [8]:
x = tf.placeholder("float", None)
y = x * 2

with tf.Session() as session:
    result = session.run(y, feed_dict={x: [1, 2, 3]})
    print(result)

[2. 4. 6.]


### forward propagation

In [10]:
import numpy as np
no_of_input=10
no_of_neuron=3
x=tf.placeholder("float",(None,no_of_input))


In [33]:
sess=tf.InteractiveSession()

In [50]:
one=tf.ones((5,5))
tf.print(one)
print(sess.run(one))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [51]:
p=tf.zeros((5,5))
tf.print(p)
print(sess.run(p))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [54]:
p=tf.fill((5,5),5.)
tf.print(p)
print(sess.run(p))
p.get_shape()

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


TensorShape([Dimension(5), Dimension(5)])

### matrix multiplication

In [56]:
z=tf.matmul(one,p)
sess.run(z)

array([[25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.]], dtype=float32)

In [19]:
import tensorflow.compat.v1 as tf 
tf.disable_v2_behavior()
x = tf.placeholder(shape=[None, 2], dtype=tf.float32)
y=tf.constant("fhgdf")

AttributeError: module 'tensorflow' has no attribute 'placeholder'